src/main/java/com/vantaa3/DraftController.java
/*
 * Copyright (c) 2013 Michael Bochenek 
 */
package com.vantaa3;

import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;

import javax.servlet.http.HttpSession;

@ManagedBean(name = "draftController")
@SessionScoped
public class DraftController {
	private Logger logger = Logger.getLogger(this.getClass().getName()); 

	@EJB
	private DraftEJB draftEJB;
	
	private String comment;

	private Draft draft;
	
	public String save(AjaxBehaviorEvent event) {
		logger.finer("sessionId: " + getSessionId());
		
		if (draft == null) {
			draft = new Draft();
			logger.finer("creating new draft object... ");
		}
		
		if (draft.getText() == null || draft.getText().length() < comment.length()) {
			draft.setText(getComment());
			draft = draftEJB.update(draft);
			logger.info("saving draft comment: " + draft);
		} else {
			logger.finer("we don't save because draft hasn't really changed.");
		}
		
		return "write.faces";
	}

	private String getSessionId() {
		FacesContext fCtx = FacesContext.getCurrentInstance();
		HttpSession session = (HttpSession) fCtx.getExternalContext().getSession(false);
		return session.getId();
	}
	
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}

src/main/java/com/vantaa3/DraftListController.java
/*
 * Copyright (c) 2013 Michael Bochenek 
 */
package com.vantaa3;

import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@ManagedBean(name = "draftListController")
@RequestScoped
public class DraftListController {
	
	@EJB
	private DraftEJB draftEJB;

	public List<Draft> getDrafts() {
		return draftEJB.loadAll();
	}

}

src/main/java/com/vantaa3/InsertController.java
/*
 * Copyright (c) 2013 Michael Bochenek 
 */
package com.vantaa3;

import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@ManagedBean(name = "insertController")
@RequestScoped
public class InsertController {
	private Logger logger = Logger.getLogger(this.getClass().getName()); 

	@EJB
	private RecommendationEJB recommendationEJB;

	private Recommendation recommendation;

	public String create() {
		recommendationEJB.create(recommendation);
		logger.info("created new " + recommendation.toString());
		recommendation = null; // is this how I ensure that I can reuse the same insert.xhtml?
		return "insert.faces";
	}
	
	public Recommendation getRecommendation() {
		if (recommendation == null) {
			recommendation = new Recommendation();
			recommendation.setRating(DEFAULT_RATING);
			recommendation.setId(recommendationEJB.loadAll().size() + 1); //TODO Recommendation.id should be @Generated!
		}
		
		return recommendation;
	}

	public void setRecommendation(Recommendation recommendation) {
		this.recommendation = recommendation;
	}
	
	private final int DEFAULT_RATING = 5;
}

src/main/java/com/vantaa3/RecommendationController.java
/*
 * Copyright (c) 2013 Michael Bochenek 
 */
package com.vantaa3;

import java.util.HashMap;
import java.util.List;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "recommendationController")
@RequestScoped
public class RecommendationController {
	private Logger logger = Logger.getLogger(this.getClass().getName()); 

	@EJB
	private RecommendationEJB recommendationEJB;

	private RankedRecommendationList list;
	
	public List<Recommendation> getAll() {
		return recommendationEJB.loadAllWithTags();
	}
	
	public List<String> getTags() {
		if (list == null) {
			list = recommendationEJB.initList();
		}
		counter++;
		return list.getTags();
	}
	
	private static long counter = 0l;
	public long getCounter() { return counter; }
	

	/**
	 * trying to fix java.lang.IllegalStateException: Cannot create a session after the response has been committed
	 * 	http://stackoverflow.com/questions/7433575/cannot-create-a-session-after-the-response-has-been-committed
	 */
	@PostConstruct
	void initialiseSession() {
		FacesContext.getCurrentInstance().getExternalContext().getSession(true);
	}
		
	public HashMap<String, List<String>> getTabularData() {
		return list.getTabularData(5,  10);
	}
	
	public List<String> getSentences(String tag) {
		long start = System.currentTimeMillis();
		logger.finer(" getting sentences for tag: " + tag);

		if (list == null) {
			list = recommendationEJB.initList();
		}
		
		List<String> retVal = list.getRecommendationSentence(tag, 5, 100);
		
		if (retVal != null && retVal.size() > 0) {
			currentSentence = retVal.get(0);
		}
		
		if (System.currentTimeMillis() - start > 0) {
			logger.finer("getSentences ms:" + (System.currentTimeMillis() - start));
		}
		
		return retVal;
	}
	
	private String currentSentence;
	public String getCurrentSentence() {
		return currentSentence;
	}
	
}

src/main/java/com/vantaa3/StatusController.java
/*
 * Copyright (c) 2013 Michael Bochenek 
 */
package com.vantaa3;

import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "statusController")
@RequestScoped
public class StatusController {
	private Logger logger = Logger.getLogger(this.getClass().getName()); 

	@EJB
	private RecommendationEJB recommendationEJB;
	
	@EJB
	private DraftEJB draftEJB;

	private RankedRecommendationList list;
	
	public List<Recommendation> getAll() {
		return recommendationEJB.loadAllWithTags();
	}
	
	public int getListSize() {
		return getAll().size();
	}
	
	public int getTotalListSize() {
		return recommendationEJB.loadAll().size();
	}

	public int getTagsSize() {
		return recommendationEJB.initList().getTags().size();
	}
	
	public int getPercentage() {
		return (getListSize() * 100) / getTotalListSize();
	}

	public int getDraftSize() {
		return draftEJB.loadAll().size();
	}

	@SuppressWarnings("deprecation")
	public String getUptime() {
		return uptime.toGMTString();
	}
	private static Date uptime = Calendar.getInstance().getTime();
	
	/**
	 * trying to fix java.lang.IllegalStateException: Cannot create a session after the response has been committed
	 * 	http://stackoverflow.com/questions/7433575/cannot-create-a-session-after-the-response-has-been-committed
	 */
	@PostConstruct
	void initialiseSession() {
		FacesContext.getCurrentInstance().getExternalContext().getSession(true);
	}
	
	public long getTimeInitList() {
		long start = System.currentTimeMillis();
		list = new RankedRecommendationList();
		
		List<Recommendation> all = getAll();
		for (Recommendation r : all) {
			String tags[] = r.getTags().split(",");
			for (String tag : tags) {
				list.add(tag, r.getSentence(), r.getRating());
			}
		}
		
		list.randomizeAndTrim();
		
		logger.finer("getTimeInitList took: " + (System.currentTimeMillis() - start));
		return (System.currentTimeMillis() - start);
	}
}

src/main/java/com/vantaa3/SurveyRequestController.java
/*
 * Copyright (c) 2013 Michael Bochenek 
 */
package com.vantaa3;

import java.util.Date;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@ManagedBean(name = "surveyRequestController")
@RequestScoped
public class SurveyRequestController {

	private Logger logger = Logger.getLogger(this.getClass().getName()); 
	
	@EJB
	private SurveyRequestEJB requestEJB;

	private String subject;
	private String owner;
	private String par1;
	private String par2;
	private String par3;
	private String par4;
	private String par5;
	private String par6;
	private String par7;
	private String par8;
	private String par9;
	private String par10;
	
	
	public String submit() {
		long start = System.currentTimeMillis();

		SurveyRequest request = new SurveyRequest();
		request.setSubject(subject);
		request.setOwner(owner);
		
		createParticipant(request, getPar1());
		createParticipant(request, getPar2());
		createParticipant(request, getPar3());
		createParticipant(request, getPar4());
		createParticipant(request, getPar5());
		createParticipant(request, getPar6());
		createParticipant(request, getPar7());
		createParticipant(request, getPar8());
		createParticipant(request, getPar9());
		createParticipant(request, getPar10());

		request = requestEJB.createSurveyRequest(request);
		
		if (System.currentTimeMillis() - start > 0) {
			logger.info("submit ms:" + (System.currentTimeMillis() - start));
		}
		return "surveyrequestcompleted.faces" + SimpleHash.generate(request.getOwner()) + "-" + request.getId();
	}
	
	
	private void createParticipant(SurveyRequest request, String participantInput) {
		
		if (participantInput != null && participantInput.trim().length() > 0) {
			SurveyResponse emptyResponse = new SurveyResponse();
			emptyResponse.setCreateDate(new Date());
			
			String email = participantInput; //TODO maybe try to smartly split out name from email
			
			emptyResponse.setEmail(email);
			emptyResponse.setRequestKey(SimpleHash.generate(email));
			request.getSurveyResponses().add(emptyResponse);
		}
	}
	
	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getPar1() {
		return par1;
	}

	public void setPar1(String par1) {
		this.par1 = par1;
	}

	public String getPar2() {
		return par2;
	}

	public void setPar2(String par2) {
		this.par2 = par2;
	}

	public String getPar3() {
		return par3;
	}

	public void setPar3(String par3) {
		this.par3 = par3;
	}

	public String getPar4() {
		return par4;
	}

	public void setPar4(String par4) {
		this.par4 = par4;
	}

	public String getPar5() {
		return par5;
	}

	public void setPar5(String par5) {
		this.par5 = par5;
	}

	public String getPar6() {
		return par6;
	}

	public void setPar6(String par6) {
		this.par6 = par6;
	}

	public String getPar7() {
		return par7;
	}

	public void setPar7(String par7) {
		this.par7 = par7;
	}

	public String getPar8() {
		return par8;
	}

	public void setPar8(String par8) {
		this.par8 = par8;
	}

	public String getPar9() {
		return par9;
	}

	public void setPar9(String par9) {
		this.par9 = par9;
	}

	public String getPar10() {
		return par10;
	}

	public void setPar10(String par10) {
		this.par10 = par10;
	}

	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}
}

src/main/java/com/vantaa3/SurveyResponseController.java
/*
 * Copyright (c) 2013 Michael Bochenek 
 */
package com.vantaa3;

import java.util.Map;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "surveyResponseController")
@RequestScoped
public class SurveyResponseController {

	private Logger logger = Logger.getLogger(this.getClass().getName()); 
	
	@EJB
	private SurveyRequestEJB requestEJB;

    @EJB
    private SurveyResponseEJB responseEJB;

    private SurveyRequest request;
    private SurveyResponse response;
    
    private String comment;

    private String question1;
    private String question2;
    private String question3;
    private String question4;
    private String question5;

	private String key;
	private String hashKeyOnly;
    private long id;
    
    private SurveyRequest getSurveyRequest() {
		long start = System.currentTimeMillis();
    	
    	if (request != null) {
    		return request;
    	}
    	
    	// example key:  http://localhost:8080/vantaa3/surveyresponse.faces?key=5b4fff6f84d72af9c572c8f7a5874e8b-1
    	// which is "requestKey-id" (where ID is the SurveyRequest.ID, NOT the SurveyResponse.ID ! )
    	if (key == null) {
        	Map<String, String[]> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterValuesMap();
        	String[] ks = params.get("key");
    		key = (ks != null && ks.length > 0) ? ks[0] : null;
    	}

		if (key != null && key.trim().length() > 0 && key.contains("-")) {
			String[] keyArray = key.split("-");
			id = Long.parseLong(keyArray[1]);
			hashKeyOnly = keyArray[0];
			request = requestEJB.load(id, hashKeyOnly);
		}

    	//logger.warning("getSurveyRequest() -> id: " + getId() + "  request.getId():" + (request == null ? " null " : request.getId()));

		if (System.currentTimeMillis() - start > 0) {
			logger.info("getSurveyRequest ms:" + (System.currentTimeMillis() - start));
		}
		
		return request;
    }
    
    private SurveyResponse getSurveyResponse() {
    	if (response != null) {
    		return response;
    	}
    	
    	if (getSurveyRequest() != null && key != null) {
    		for (SurveyResponse r : request.getSurveyResponses()) {
    			String generatedKey = SimpleHash.generate(r.getEmail());
    			
    			//logger.warning(" generatedKey: " + generatedKey);

            	if (hashKeyOnly.equals(generatedKey)) {
            		response = r;
            		return response;
            	}
    		}
    		
    		//logger.warning(" getSurveyResponse() ->  we shouldn't get here: " + request.getSurveyResponses().size());
    	}

    	
		return null;
    }
    
    /**
     * Very important - if the request has been submitted, show in ready only mode.
     * @return
     */
    public boolean isReadOnly() {
    	boolean val = getSurveyResponse() == null ? false : getSurveyResponse().getSubmitDate() != null;
    	//logger.info("isreadonly " + val);
    	return val;
    }
    
    public String getIdString() {
    	return "" + (getSurveyResponse() == null ? "getSurveyResponse returned null " : getSurveyResponse().getId());
    }

    public String getYou() {
    	return "" + (getSurveyResponse() == null ? "getSurveyResponse returned null " : getSurveyResponse().getEmail());
    }

    public String getOwner() {
    	return "" + (getSurveyRequest() == null ? "getSurveyResponse returned null " : getSurveyRequest().getOwner());
    }
    
    public String getSubject() {
    	return "" + (getSurveyRequest() == null ? "getSurveyResponse returned null " : getSurveyRequest().getSubject());
    }
    
	public String submit() {
		long start = System.currentTimeMillis();

		if (getSurveyResponse() == null) {
			return "nothingtosave.faces";
		}
		
		//TODO
		// MailSender.test(comment); --> works at 2:04pm Oct 7
		
		getSurveyResponse().setComment(comment);
		
		responseEJB.save(getSurveyResponse());
		
		if (System.currentTimeMillis() - start > 0) {
			logger.info("submit ms:" + (System.currentTimeMillis() - start));
		}
		
		return "surveyresponsecompleted.faces"; // this would return the next page that we would go to...
	}

	
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getQuestion1() {
		return question1;
	}

	public void setQuestion1(String question1) {
		this.question1 = question1;
	}

	public String getQuestion2() {
		return question2;
	}

	public void setQuestion2(String question2) {
		this.question2 = question2;
	}

	public String getQuestion3() {
		return question3;
	}

	public void setQuestion3(String question3) {
		this.question3 = question3;
	}

	public String getQuestion4() {
		return question4;
	}

	public void setQuestion4(String question4) {
		this.question4 = question4;
	}

	public String getQuestion5() {
		return question5;
	}

	public void setQuestion5(String question5) {
		this.question5 = question5;
	}

    public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return id;
	}

}

src/main/java/com/vantaa3/xing/XingRecommendationController.java
/*
 * Copyright (c) 2013 Michael Bochenek 
 */
package com.vantaa3.xing;

import java.util.List;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@ManagedBean(name = "xingRecommendationController")
@RequestScoped
public class XingRecommendationController {
	private Logger logger = Logger.getLogger(this.getClass().getName()); 
	
	@EJB
	private XingRecommendationEJB xingRecEJB;

	private List<XingRecommendation> writtenRecommendations = null;
	private List<XingRecommendation> receivedRecommendations = null;

	public int getWrittenRecommendationsCount() {
		return getWrittenRecommendations().size();
	}
	
	public List<XingRecommendation> getWrittenRecommendations() {
		long startTS = System.currentTimeMillis();
		if (writtenRecommendations == null) {
			writtenRecommendations = xingRecEJB.loadByOwner("mike"); //TODO from session or something?
		}
		logger.info("writtenRecommendations loaded "
				+ writtenRecommendations.size() + " recs in "
				+ (System.currentTimeMillis() - startTS) + " ms");
		
		return writtenRecommendations;
	}
	
	public int getReceivedRecommendationsCount() {
		return getReceivedRecommendations().size();
	}

	public List<XingRecommendation> getReceivedRecommendations() {
		long startTS = System.currentTimeMillis();
		if (receivedRecommendations == null) {
			receivedRecommendations = xingRecEJB.loadBySubject("valentin"); //TODO from session or something?
		}
		logger.info("receivedRecommendations loaded "
				+ receivedRecommendations.size() + " recs in "
				+ (System.currentTimeMillis() - startTS) + " ms");
		
		return receivedRecommendations;
	}

}

src/main/webapp/about.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:ui="http://java.sun.com/jsf/facelets">
      
<h:body>

<ui:composition template="commonlayout.xhtml">
   <ui:define name="content">

    <h:form>
    <p>#{msg.haveyouever}</p>
	<p>#{msg.heretohelp}</p>
	</h:form>

  </ui:define>
</ui:composition>

</h:body>
</html>

src/main/webapp/commoncontent.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets"
      >
    <body>
	    <ui:composition>
 
		<h1>This is default content (that we would never see)</h1>
 
	    </ui:composition>
    </body>
</html>

src/main/webapp/status.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
      
<h:body>

<ui:composition template="plainlayout.xhtml">
   <ui:define name="content">
    <h:form>
    	<div>status page (troubleshooting only)</div> <br/><br/>
    
    	<table>
    	    <tr>
				<td><h:outputLabel value="total recommendations"/></td>
				<td>#{statusController.totalListSize}</td>
			</tr>
    	    <tr>
				<td><h:outputLabel value="recommendations"/></td>
				<td>#{statusController.listSize}</td>
			</tr>
    	    <tr>
				<td><h:outputLabel value="percentage"/></td>
				<td>#{statusController.percentage}%</td>
			</tr>
    	    <tr>
				<td><h:outputLabel value="time (ms)"/></td>
				<td>#{statusController.timeInitList}</td>
			</tr>
    	    <tr>
				<td><h:outputLabel value="counter"/></td>
				<td>#{recommendationController.counter}</td>
			</tr>
    	    <tr>
				<td><h:outputLabel value="tags size"/></td>
				<td>#{statusController.tagsSize}</td>
			</tr>
    	    <tr>
				<td><h:outputLabel value="draft size"/></td>
				<td>#{statusController.draftSize}</td>
			</tr>
    	    <tr>
				<td><h:outputLabel value="up since"/></td>
				<td>#{statusController.uptime}</td>
			</tr>
		</table>
		
	</h:form>
  </ui:define>
</ui:composition>

</h:body>
</html>

src/main/webapp/xing.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>

<ui:composition template="xinglayout.xhtml">
   <ui:define name="content">
      <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js"></script>
      <script type="text/javascript">
			function autosave() { 
				var newVal = CKEDITOR.instances[($('#ckeditorparent'))[0].firstChild.id].getData();
				($('#somedataparent'))[0].firstChild.value = (newVal);
				if (newVal.length > _newValLen) {
					($('#autosavedraft_td'))[0].firstChild.click();
					_newValLen = newVal.length;
				}
			}
			var _newValLen = 0;
			$(function(){
		        CKEDITOR.replace(($('#ckeditorparent'))[0].firstChild.id, { customConfig: '/vantaa/js/ckeditor/config.js' } );
				window.setInterval(autosave, 5000);
			});
      </script>

      <ul class="subnav">
        <li class="active"><strong><a href="xing.faces">Write New</a></strong></li>
        <li><a href="xing_received.faces">Received (<h:outputText value="#{xingRecommendationController.receivedRecommendationsCount}" />)</a></li>
        <li><strong><a href="xing_written.faces">Written (<h:outputText value="#{xingRecommendationController.writtenRecommendationsCount}" />)</a></strong></li>
      </ul>

      <h:form>
         <ui:include  src="tagmagic.xhtml"/>
         <div id="ckeditorparent"><h:inputTextarea value="#{surveyResponseController.comment}" id="editor1" /></div>
         <div id="somedataparent"><h:inputHidden id="someData" value="#{draftController.comment}" /></div>
         <div style="display:none" id="autosavedraft_td"><h:commandButton id="savedraftbtn" accesskey="s" value="Save"  >
            <f:ajax event="click" execute="someData"  listener="#{draftController.save}" />
            </h:commandButton>
         </div>
         
      </h:form>
   </ui:define>

</ui:composition>
	
</h:body>
</html>

src/main/webapp/xing_received.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>

<ui:composition template="xinglayout.xhtml">
   <ui:define name="content">
      <ul class="subnav">
        <li><strong><a href="xing.faces">Write New</a></strong></li>
        <li class="active"><a href="xing_received.faces">Received (<h:outputText value="#{xingRecommendationController.receivedRecommendationsCount}" />)</a></li>
        <li><strong><a href="xing_written.faces">Written (<h:outputText value="#{xingRecommendationController.writtenRecommendationsCount}" />)</a></strong></li>
      </ul>

    <h:dataTable class="data-table" rules="all" value="#{xingRecommendationController.receivedRecommendations}" var="rec">
    	
    	<h:column>
			<f:facet name="header"><h:outputText value="create data"/></f:facet>
			<h:outputText value="#{rec.createDate}" ><f:convertDateTime pattern="dd.MM.yyyy" /></h:outputText>
			<h:outputText value=" from #{rec.subject}"/>
		</h:column>

    	<h:column>
			<f:facet name="header"><h:outputText value="text"/></f:facet>
			<h:outputText value="#{rec.text}" escape="false" />
		</h:column>

	</h:dataTable>
         
   </ui:define>

</ui:composition>
	
</h:body>
</html>

src/main/webapp/xing_written.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>

<ui:composition template="xinglayout.xhtml">
   <ui:define name="content">
      <ul class="subnav">
        <li><strong><a href="xing.faces">Write New</a></strong></li>
        <li><a href="xing_received.faces">Received (<h:outputText value="#{xingRecommendationController.receivedRecommendationsCount}" />)</a></li>
        <li class="active"><strong><a href="xing_written.faces">Written (<h:outputText value="#{xingRecommendationController.writtenRecommendationsCount}" />)</a></strong></li>
      </ul>

    <h:dataTable class="data-table" rules="all" value="#{xingRecommendationController.writtenRecommendations}" var="rec">
    	
    	<h:column>
			<f:facet name="header"><h:outputText value="create data"/></f:facet>
			<h:outputText value="#{rec.createDate}" ><f:convertDateTime pattern="dd.MM.yyyy" /></h:outputText>
			<h:outputText value=" for #{rec.subject}"/>
		</h:column>

    	<h:column>
			<f:facet name="header"><h:outputText value="text"/></f:facet>
			<h:outputText value="#{rec.text}" escape="false" />
		</h:column>

	</h:dataTable>
         
   </ui:define>

</ui:composition>
	
</h:body>
</html>